from collections.abc import Iterable, Iterator
from typing import Self

class Trie:
    def __init__(self, iterable: Iterable[str] = ()) -> None: ...

    def add(self, element: str) -> None: ...

    def remove(self, element: str) -> None: ...

    def discard(self, element: str) -> None: ...

    def pop(self) -> str: ...

    def clear(self) -> None: ...

    def __len__(self) -> int: ...

    def __contains__(self, element: object) -> bool: ...

    def __iter__(self) -> Iterator[str]: ...

    def __reversed__(self) -> Iterator[str]: ...

    def __eq__(self, other: object) -> bool: ...

    def __or__(self, other: object) -> object: ...

    def __and__(self, other: object) -> object: ...

    def __sub__(self, other: object) -> object: ...

    def __xor__(self, other: object) -> object: ...

    def __ior__(self, other: object) -> Self: ...

    def __iand__(self, other: object) -> Self: ...

    def __isub__(self, other: object) -> Self: ...

    def __ixor__(self, other: object) -> Self: ...
